#!/bin/bash

## THE FIRST TIER IS ENERGY  OPTIMIZATION AT A MINIMAL BASIS
FIRST_TIER=$(sbatch h2_geoms_batch.sh)

## SECOND TIER IS ONLY GEOM OPTS FOR MINIMAL BASIS BUT DEPENDS ON WAVEFUNCTION
## GUESSES FROM TIER 1
SECOND_TIER=$(sbatch --dependency=afterok:$FIRST_TIER  h2_opt_batch.sh)
## THIRD TIER IS TWO GROUPS: 1.  SOLVATED GEOMETRY OPTS FOR MINIMAL BASIS
##                           2.  GAS PHASE GEOMETRY OPTS AT HIGHER THEORY LEVELS
## DEPENDENCIES:             1.  TIER 2 ONLY
##                           2.  TIER 2 ONLY

## FOURTH TIER IS FREQUENCY CALCULATIONS FOR THE MINIMAL BASIS JOB
##
